### ISSUE TITLE
Null user ID when getting circle details in background job

### ISSUE THREAD

**Issue by mokkin** [nextcloud/circles#563]
### Steps to reproduce
Error in logs visible

### Expected behaviour
no error, but one user ("username") complains about data loss in deck app

### Actual behaviour
Error in logs visible

## Server configuration detail

**Operating system:** Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.7.33

**PHP version:** 

7.4.14
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, gmp, SPL, iconv, session, json, mbstring, pcntl, standard, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, mysqlnd, cgi-fcgi, imagick, curl, gd, mysqli, PDO, pdo_mysql, xsl, sqlite3, intl, sodium, ldap, tidy, pdo_pgsql, pdo_sqlite, igbinary, redis, ionCube Loader, Zend OPcache

**Nextcloud version:** 20.0.8 - 20.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - circles: 0.20.7
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.4
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_markdown: 2.3.2
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - groupfolders: 8.2.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.2
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - occweb: 0.0.7
 - password_policy: 1.10.1
 - passwords: 2021.2.0
 - photos: 1.2.3
 - previewgenerator: 3.1.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.6
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - encryption
 - maps
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.8.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app.mail.server-side-cache.enabled": true,
    "filelocking.enabled": true,
    "0": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "theme": "",
    "loglevel": 0,
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "mysql.utf8mb4": true,
    "htaccess.IgnoreFrontController": true,
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb",
        "issuetemplate"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0

**Operating system:** Ubuntu 20.04

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
[core] Error: TypeError: Argument 2 passed to OCA\Circles\Db\CirclesRequest::getCircle() must be of the type string, null given, called in /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/apps/circles/lib/Service/CirclesService.php on line 277 at <<closure>>

0. /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/apps/circles/lib/Service/CirclesService.php line 277
   OCA\Circles\Db\CirclesRequest->getCircle("7744cddd5e4877", null, 1, "", true)
1. /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/apps/circles/lib/Api/v1/Circles.php line 265
   OCA\Circles\Service\CirclesService->detailsCircle("7744cddd5e4877", true)
2. /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/apps/deck/lib/Service/PermissionService.php line 265
   OCA\Circles\Api\v1\Circles::detailsCircle("7744cddd5e4877", true)
3. /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/apps/deck/lib/Activity/ActivityManager.php line 450
   OCA\Deck\Service\PermissionService->findUsers(28)
4. /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/apps/deck/lib/Activity/ActivityManager.php line 265
   OCA\Deck\Activity\ActivityManager->sendToUsers(OC\Activity\Event {})
5. /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/apps/deck/lib/Cron/CardDescriptionActivity.php line 58
   OCA\Deck\Activity\ActivityManager->triggerEvent("deck_card", OCA\Deck\Db\Card {id: 162}, "card_update_description", {before: "",afte ... "}, "usernamw")
6. /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/lib/private/BackgroundJob/Job.php line 52
   OCA\Deck\Cron\CardDescriptionActivity->run(null)
7. /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud/cron.php line 127
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2021-03-03T14:25:12+01:00
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by eneiluj** [comment]
@juliushaertl Does it ring a bell? Do you think this kind of error can be fixed on Deck's side?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/circles/blob/master/lib/Service/CirclesService.php#L144-L149

Injecting the userId only works in controllers. Everything else can be called without a user anyway e.g. via background jobs like here.
In this case it's preparing information for an activity, so `IActivityManager::getCurrentUser` gives you the user which should be used to check access and details: https://github.com/nextcloud/server/blob/master/lib/public/Activity/IManager.php#L167-L176

**Comment by juliushaertl** [comment]
I figured out I already had uncommitted changes in my local repo exactly for this and pushed them to https://github.com/nextcloud/circles/pull/566

**Comment by doobry-systemli** [comment]
Unfortunately this issue still exists in Nextcloud 21.0.1:

```yaml
{
  "Exception": "TypeError",
  "Message": "Argument 2 passed to OCA\\Circles\\Db\\CirclesRequest0:0:0:0:0:0:0:0getCircle() must be of the type string, null given, called in /var/www/cloud.example.org/nextcloud-21.0.1/apps/circles/lib/Service/CirclesService.php on line 277",
  "Code": 0,
  "Trace": [
    {
      "file": "/var/www/cloud.example.org/nextcloud-21.0.1/apps/circles/lib/Service/CirclesService.php",
      "line": 277,
      "function": "getCircle",
      "class": "OCA\\Circles\\Db\\CirclesRequest",
      "type": "->",
      "args": [
        "4346fee3223491",
        null,
        1,
        "",
        true
      ]
    },
    {
      "file": "/var/www/cloud.example.org/nextcloud-21.0.1/apps/circles/lib/Api/v1/Circles.php",
      "line": 265,
      "function": "detailsCircle",
      "class": "OCA\\Circles\\Service\\CirclesService",
      "type": "->",
      "args": [
        "4346fee3223491",
        true
      ]
    },
    {
      "file": "/var/www/cloud.example.org/nextcloud-21.0.1/apps/deck/lib/Service/PermissionService.php",
      "line": 265,
      "function": "detailsCircle",
      "class": "OCA\\Circles\\Api\\v1\\Circles",
      "type": "0:0:0:0:0:0:0:0",
      "args": [
        "4346fee3223491",
        true
      ]
    },
    {
      "file": "/var/www/cloud.example.org/nextcloud-21.0.1/apps/deck/lib/Notification/NotificationHelper.php",
      "line": 98,
      "function": "findUsers",
      "class": "OCA\\Deck\\Service\\PermissionService",
      "type": "->",
      "args": [
        78
      ]
    },
    {
      "file": "/var/www/cloud.example.org/nextcloud-21.0.1/apps/deck/lib/Cron/ScheduledNotifications.php",
      "line": 62,
      "function": "sendCardDuedate",
      "class": "OCA\\Deck\\Notification\\NotificationHelper",
      "type": "->",
      "args": [
        {
          "id": 2376,
          "__class__": "OCA\\Deck\\Db\\Card"
        }
      ]
    },
    {
      "file": "/var/www/cloud.example.org/nextcloud-21.0.1/lib/private/BackgroundJob/Job.php",
      "line": 52,
      "function": "run",
      "class": "OCA\\Deck\\Cron\\ScheduledNotifications",
      "type": "->",
      "args": [
        null
      ]
    },
    {
      "file": "/var/www/cloud.example.org/nextcloud-21.0.1/cron.php",
      "line": 128,
      "function": "execute",
      "class": "OC\\BackgroundJob\\Job",
      "type": "->",
      "args": [
        {
          "__class__": "OC\\BackgroundJob\\JobList"
        },
        {
          "__class__": "OC\\Log"
        }
      ]
    }
  ],
  "File": "/var/www/cloud.example.org/nextcloud-21.0.1/apps/circles/lib/Db/CirclesRequest.php",
  "Line": 192,
  "CustomMessage": "Error while running background job (class: OCA\\Deck\\Cron\\ScheduledNotifications, arguments: )"
}
```

I just reported this as https://github.com/nextcloud/deck/issues/2955
